#Search for your_MES or your_TDE to find placeholders
spring:
  profiles:
    active:
      - development

  datasource:
    url: jdbc:postgresql://${MES_DB_HOST:your_MES_db_host}:${MES_DB_PORT:your_MES_db_port}/${MES_DB_NAME:your_MES_db_name}
    username: ${MES_DB_USERNAME:your_MES_db_username}
    password: ${MES_DB_PASSWORD:your_MES_db_password}
    driverClassName: "org.postgresql.Driver"
  jpa:
    open-in-view: false
    databasePlatform: "org.hibernate.dialect.PostgreSQLDialect"

jwt:
  secretKey: ${TDE_JWT_SECRET_KEY:your_TDE_jwt_secret_key}

aws:
  mqtt:
      clientId: ${MES_MQTT_CLIENT_ID:your_MES_mqtt_client_id}
      clientEndpoint: ${MES_MQTT_CLIENT_ENDPOINT:your_MES_mqtt_client_endpoint}
      awsRegion: ${MES_MQTT_AWS_REGION:your_MES_mqtt_aws_region}
      awsAccessKeyId: ${TDE_AWS_ACCESS_KEY_ID:your_TDE_user_aws_access_key_id}
      awsSecretAccessKey: ${TDE_AWS_SECRET_ACCESS_KEY:your_TDE_user_aws_secret_access_key}