#nginx
#server:
  #port: 5000

server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/mesclouddb #change this to your database url
    username: postgres #change this to your database username
    password: Publico1990 #change this to your database password
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update #don't create database, you have to create it first in Postgres, and then it will create tables. then we have to change to update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
