server:
  port: 5000

spring:
  datasource:
    url: dbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    open-in-view: false

aws:
  mqtt:
    clientId: ${MQTT_CLIENT_ID}
    clientEndpoint: ${MQTT_CLIENT_ENDPOINT}
    awsAccessKeyId: ${AWS_ACCESS_KEY_ID}
    awsSecretAccessKey: ${AWS_SECRET_ACCESS_KEY}

mes:
  mqtt:
    countProtocolTopic: "MASILVA/OBO/PROTOCOL_COUNT_V0"