server:
  port: 5000

jwt:
  secretKey: ${SECURITY_KEY}

spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driverClassName: "org.postgresql.Driver"
  jpa:
    open-in-view: false
    databasePlatform: "org.hibernate.dialect.PostgreSQLDialect"

aws:
  mqtt:
    clientId: ${MQTT_CLIENT_ID}
    clientEndpoint: ${MQTT_CLIENT_ENDPOINT}
    awsRegion: ${MQTT_AWS_REGION}
    awsAccessKeyId: ${AWS_ACCESS_KEY_ID}
    awsSecretAccessKey: ${AWS_SECRET_ACCESS_KEY}

mes:
  mqtt:
    protCountBackendTopic: "MASILVA/OBO/PROTOCOL_COUNT_V0/BE"
    protCountPlcTopic: "MASILVA/OBO/PROTOCOL_COUNT_V0/PLC"
  security:
    allowedOrigin: "https://www.mescloud.pt"