#nginx
server:
  port: 5000

#server:
#  port: 8081

  datasource:
    url: dbc:postgresql://${DB_HOST}:${DB_PORT}/${DATABASE_NAME} #change this to your database url
    username: ${DB_USERNAME} #change this to your database username
    password: ${DB_PASSWORD} #change this to your database password
spring:
  jpa:
    open-in-view: false

#spring:
#  datasource:
#    url: jdbc:h2:mem:mydb
#    username: sa
#    password: password
#    driverClassName: org.h2.Driver
#    jpa:
#      spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
