#nginx
server:
  port: 80

  #server:
  #port: 8081

#spring:
#  datasource:
#    url: jdbc:h2:mem:mydb
#    username: sa
#    password: password
#    driverClassName: org.h2.Driver
#    jpa:
#      spring.jpa.database-platform: org.hibernate.dialect.H2Dialect

#  datasource:
#    url: jdbc:postgresql://localhost:5432/mesclouddb #change this to your database url
#    username: postgres #change this to your database username
#    password: Publico1990 #change this to your database password
#  jpa:
#    show-sql: true
#    hibernate:
#      ddl-auto: update #don't create database, you have to create it first in Postgres, and then it will create tables. then we have to change to update
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.PostgreSQLDialect
