name: Main | Production CI/CD

on:
  push:
    branches:
      - main # Adjust as needed for your main branch name
  pull_request:
    branches:
      - main # Adjust as needed for your main branch name
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Download JAR
        uses: actions/download-artifact@v2
        with:
          name: artifact

      - name: Deploy to AWS Beanstalk (Prod)
        # You need to replace the deployment action with the appropriate deployment tool for your project
        # Here, I'm assuming you're deploying to AWS Elastic Beanstalk
        uses: einaregilsson/beanstalk-deploy@v13
        with:
          aws_access_key: ${{ secrets.PROD_AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.PROD_AWS_SECRET_ACCESS_KEY }}
          aws_session_token: ${{ secrets.AWS_SESSION_TOKEN }}
          use_existing_version_if_available: true
          application_name: mescloud
          environment_name: Mescloud
          version_label: ${{ github.SHA }}
          region: eu-west-1
          deployment_package: mescloud-0.0.1-SNAPSHOT.jar
