name: Main | Production CI/CD

on:
  push:
    branches:
      - '*'
      - 'feature/*'
      - 'bug/*'
  pull_request:
  workflow_dispatch:

env:
  DB_HOST: ${{ vars.DB_HOST }}
  DB_PORT: ${{ vars.DB_PORT }}
  DB_NAME: ${{ vars.DB_NAME }}
  DB_USERNAME: ${{ vars.DB_USERNAME }}
  DB_PASSWORD: ${{ vars.DB_PASSWORD }}
  MQTT_CLIENT_ID: ${{ secrets.MQTT_CLIENT_ID }}
  MQTT_CLIENT_ENDPOINT: ${{ secrets.MQTT_CLIENT_ENDPOINT }}
  MQTT_AWS_REGION: ${{ secrets.MQTT_AWS_REGION }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  SPRING_PROFILES_ACTIVE: "production"
  SECURITY_KEY: ${{ secrets.SECURITY_KEY }}

jobs:

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: build-and-analyze
    steps:
      - name: Download JAR
        uses: actions/download-artifact@v2
        with:
          name: artifact

      - name: Deploy to AWS Beanstalk (Prod)
        uses: einaregilsson/beanstalk-deploy@v13
        with:
          aws_access_key: ${{ secrets.PROD_AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.PROD_AWS_SECRET_ACCESS_KEY }}
          aws_session_token: ${{ secrets.AWS_SESSION_TOKEN }}
          use_existing_version_if_available: true
          application_name: mescloud
          environment_name: Mescloud
          version_label: ${{ github.SHA }}
          region: eu-west-1
          deployment_package: mescloud-0.0.1-SNAPSHOT.jar
        if: github.ref == 'refs/heads/main'

      - name: Deploy to AWS Beanstalk (Development)
        uses: einaregilsson/beanstalk-deploy@v13
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_session_token: ${{ secrets.AWS_SESSION_TOKEN }}
          use_existing_version_if_available: true
          application_name: mescloud
          environment_name: Mescloud-env
          version_label: ${{ github.SHA }}
          region: eu-west-3
          deployment_package: mescloud-0.0.1-SNAPSHOT.jar
        if: github.ref == 'refs/heads/development'
